Retry unmounts if the mount point is busy
A mount point in the sandbox can be left busy for a variety of reasons,
and in particular because of processes that haven't yet finished
executing after being killed.

We were already waiting for the file systems to disappear with a retry
loop, so extend the loop to cover the umount(8) calls too.

diff --git a/sandbox.subr.in b/sandbox.subr.in
--- a/sandbox.subr.in
+++ b/sandbox.subr.in
@@ -256,15 +256,19 @@ sandbox_unmount_dirs() {
         | while read dir
     do
         shtk_cli_debug "Unmounting ${dir}"
-        umount ${force_flag} "${dir}" || shtk_cli_error "Failed to unmount" \
-            "sandbox"
         local retries=50
-        while [ ${retries} -gt 0 ] && sandbox_has_mounts "${dir}"; do
+        while [ ${retries} -gt 0 ]; do
+            # This may fail e.g. if the file system is busy.  We don't check for
+            # error here because we want to retry this a few times.  We will
+            # only determine that the unmount failed if we run out of tries.
+            umount ${force_flag} "${dir}" || shtk_cli_debug "umount failed"
+            sandbox_has_mounts "${dir}" || break
+
             shtk_cli_debug "Mount point ${dir} has not disappeared yet; waiting"
             sleep .1
             retries=$((${retries} - 1))
         done
-        [ ${retries} -gt 0 ] || shtk_cli_error "Unmount of ${dir} failed"
+        [ ${retries} -gt 0 ] || shtk_cli_error "Failed to unmount ${dir}"
     done
 }
 
